### ISSUE TITLE
Remove OpenAL dependency and fast-forward

### ISSUE THREAD

**Issue by a3f** [Martinfx/FreeBSD-Ports#1]
https://github.com/Martinfx/FreeBSD-Ports/blob/cc550f58a954f72515f2811e16de360a707e6ce5/raylib/Makefile#L16

Not need anymore.

https://github.com/Martinfx/FreeBSD-Ports/blob/cc550f58a954f72515f2811e16de360a707e6ce5/raylib/distinfo#L2

Upstream fixed format of `Libs.private` in `raylib.pc` on FreeBSD, please fast-forward.

**Comment by Martinfx** [comment]
Raylib have release version 1.9.1-dev but havent patches for Freebsd and because i am made pre-release because waiting for new release in up-stream then switch to up-stream

**Comment by Martinfx** [comment]
Thank you.
